# Application
spring:
  application:
    name: flight-inventory
    # Database (MySQL)
  datasource:
    url: jdbc:mysql://localhost:3306/airxelerate_inventory_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9090

# JWT Configuration
jwt:
  secret: 578c4249e79647b6d1dc9fe66a8c170e16a1a66df47fe6e85ff17516febb0740
  expiration: 3600000

# Logging
logging:
  level:
    com.airxelerate.inventory: DEBUG
    org.springframework.security: DEBUG

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.airxelerate.inventory.controller
  paths-to-match: /api/**
  show-actuator: false
