# Application
spring.application.name=flight-inventory
server.port=9090

# Database (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/airxelerate_inventory_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=578c4249e79647b6d1dc9fe66a8c170e16a1a66df47fe6e85ff17516febb0740
jwt.expiration=3600000

# Logging
logging.level.com.airxelerate.inventory=DEBUG
logging.level.org.springframework.security=DEBUG

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.airxelerate.inventory.controller
springdoc.paths-to-match=/api/**
springdoc.show-actuator=false